---
- name: Image Mode CI/CD - AAP | Playbook for AAP2 Controller resources configuration
  hosts: localhost
  vars_files:
    - demo-setup-vars.yml
    - internal-vars.yml
  vars:
    aap_hostname: "{{ aap2_controller_url }}"
    aap_username: "{{ aap2_controller_username }}"
    aap_password: "{{ aap2_controller_password }}"
    aap_validate_certs: false
    aap_configuration_async_retries: 60
  roles:
    - role: infra.aap_configuration.dispatch
