---
collections:
  - ansible.controller
  - ansible.posix
  - community.general
  - containers.podman
roles:
  - name: role_aap_controller_setup
    src: https://github.com/kubealex/role_aap_controller_setup.git
