---
- name: Image Mode CI/CD - AAP | Build RHEL Image Mode container
  hosts: build_host
  tasks:
    - name: Image Mode CI/CD - AAP | Set working directory
      ansible.builtin.set_fact:
        workdir: "{{ working_dir | default(lookup('env','HOME') + '/rhel-image-mode', true) }}"

    - name: Image Mode CI/CD - AAP | Ensure packages are up to date
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Image Mode CI/CD - AAP | Ensure Podman is present
      become: true
      ansible.builtin.dnf:
        name: container-tools
        state: present

    - name: Image Mode CI/CD - AAP | Create local working directory
      ansible.builtin.file:
        path: "{{ workdir }}/output"
        state: directory
        mode: "0775"
